version: "3.8"

services:
  frontend:
    build:
      context: .
      args:
        NODE_VERSION: "${NODE_VERSION}"
        USER_NAME: "${DOCKER_USER_NAME}"
        USER_UID: "${DOCKER_USER_UID}"
        USER_GID: "${DOCKER_USER_GID}"
    volumes:
      - .:/code
      - node_modules:/code/node_modules
      - elm-stuff:/code/elm-stuff
    environment:
      NODE_ENV: "development"
      APP_NAME: "${APP_NAME}"
      APP_SITE_NAME: "${APP_SITE_NAME}"
      APP_DOMAIN: "${APP_DOMAIN}"
      ASSET_PATH: "${ASSET_PATH}"
    ports:
      - "${HOST_PORT}:3000"
    command:
      - "sleep"
      - "infinity"

volumes:
  elm-stuff:
    external: false
    name: "${APP_NAME}_elm-stuff"

  node_modules:
    external: false
    name: "${APP_NAME}_node_modules"
